import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/security';
import { connectDB } from '@/lib/mongodb';
import { Agreement } from '@/lib/models';

export const runtime = 'nodejs';

export async function GET(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { id } = await params;
        const authResult = await requireAuth(request);
        if (!authResult.success) {
            return NextResponse.json({ error: authResult.error }, { status: authResult.status });
        }

        await connectDB();

        const agreement = await Agreement.findById(id)
            .populate('parties', 'name email role')
            .populate('startupId', 'name industry')
            .lean();

        if (!agreement) {
            return NextResponse.json({ error: 'Agreement not found' }, { status: 404 });
        }

        // Security: Only involved parties or admins
        const isParty = (agreement as any).parties.some(
            (party: any) => party._id.toString() === authResult.user.userId
        );

        if (!isParty && authResult.user.role !== 'admin') {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 403 });
        }

        // Generate a plain-text agreement snapshot (PDF generation would require pdf-lib)
        const a = agreement as any;
        const partyNames = a.parties.map((p: any) => `${p.name} (${p.role})`).join(', ');
        const startupName = a.startupId?.name || 'N/A';
        const createdAt = new Date(a.createdAt).toLocaleDateString('en-US', {
            year: 'numeric', month: 'long', day: 'numeric',
        });

        const content = [
            'ALLOYSPHERE AGREEMENT SNAPSHOT',
            '─'.repeat(40),
            '',
            `Agreement ID: ${a._id}`,
            `Type: ${a.type || 'General Agreement'}`,
            `Status: ${a.status}`,
            `Created: ${createdAt}`,
            '',
            `Startup: ${startupName}`,
            `Industry: ${a.startupId?.industry || 'N/A'}`,
            '',
            'PARTIES',
            '─'.repeat(40),
            partyNames,
            '',
            'TERMS',
            '─'.repeat(40),
            a.terms || 'No terms specified.',
            '',
            'SIGNATURES',
            '─'.repeat(40),
            ...(a.signatures || []).map((sig: any) =>
                `${sig.name || 'Unknown'}: ${sig.signed ? `Signed on ${new Date(sig.signedAt).toLocaleDateString()}` : 'Pending'}`
            ),
            '',
            '─'.repeat(40),
            'This is a digital snapshot generated by AlloySphere.',
            'Document integrity is verified through platform audit trail.',
        ].join('\n');

        return new NextResponse(content, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
                'Content-Disposition': `attachment; filename="agreement-${id}.txt"`,
            },
        });
    } catch (error) {
        console.error('Agreement PDF Error:', error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
